"""Phase 3c: Bayes-factor sanity mini-campaign on synthetic catalogs.

Format ``gwpop-search-phase3-evidence-check-1.0``. It checks, on catalogs whose
answer is known, that the dynesty evidence pipeline gives sensible Bayes
factors for two exactly nested atoms of the model graph:

* ``chieff.mean.linear_q`` adds ``chi_mu_q_slope`` ~ U(-0.6, 0.6), pivot 0.7;
* ``pairing.beta.linear_m1`` adds ``beta_q_m1_slope`` ~ U(-0.3, 0.3), pivot 30.

Both children equal the root at slope 0 and the child's conditional prior of
the shared parameters is the root prior, so the Savage-Dickey density ratio is
exact (Verdinelli-Wasserman factor 1; design/MODEL_COMPARISON_MATH.md, Sec. 2
and 4).

Design (pre-declared and recorded in the plan)
----------------------------------------------
(a) Null cases: the ``n_catalogs`` Phase-3 v2 catalogs (the recovery
    campaign's seed pairs and survey, generated from the root truth). On each:
    F3-style evidence (``R`` independent dynesty runs, the campaign's dynesty
    settings with ``slices = 2 * (3 + ndim)`` of each model) for the
    declarative root ``compile_model_spec(baseline_model_spec())`` and for both
    children (the registered mutation applied to the root). Reported:
    ``ln BF(child/root) = mean lnZ_child - mean lnZ_root`` with, per
    MODEL_COMPARISON_MATH.md 9.1(6),
    ``sigma^2 = sigma_NS,child^2 / R_child + sigma_NS,root^2 / R_root``,
    ``sigma_NS,M = max(repeat std, mean logzerr, kappa_hat sqrt(H_M / nlive))``,
    and the Savage-Dickey cross-check ``ln BF_SDDR = ln pi(0) - ln p(0 | D)``
    (NS-weighted Gaussian KDE of the child's pooled slope posterior at 0; no
    reflection, 0 is interior). The Monte-Carlo-likelihood term ``sigma_MC,ab``
    of 9.1(6) is not computed here; it is common to both routes and so does not
    belong in the SDDR tolerance (design Sec. 4.4), but the reported
    ``ln_bf_sigma`` is consequently a nested-sampling-only uncertainty and a
    lower bound on the full 9.1(6) error. The literal formula of the original
    task text, ``sqrt(cons_child^2 + cons_root^2)`` with ``cons = max(repeat
    std, max reported error)``, is recorded beside it as
    ``ln_bf_sigma_task_text``: it is the error of a single run rather than of
    the mean of ``R``, i.e. larger by about ``sqrt(R)``, and no check uses it.
(b) Injected cases: one catalog per atom drawn from the child model with the
    slope at ``0.9 x`` the upper prior bound (0.54 and 0.27) and every other
    hyperparameter at the root truth, generated by the DAG-consistent
    structured generator :func:`gwpop_search.scouts.synthetic.generate_structured_scout_dataset`
    (it honours ``observation_model="noisy_observation"``: one noise
    realisation per system, detection on observed data, PE drawn given the
    observation). Root and child evidence as in (a).

Before any fit, ``compile_model_spec(baseline_model_spec())`` and
``GwcatChiEffBBHModel`` are compared on every catalog's PE and selection
samples at the truth and at seeded prior draws (identical support and
``|delta log p| <= 1e-10``); a mismatch aborts the check.

Engineering pass rule (:class:`EvidenceCheckPassRule`)
-----------------------------------------------------
1. every fit is numerically valid under the F3-level gates
   (:meth:`NSRecoveryAcceptanceCriteria.f3_level`);
2. ``ln BF(child/root) < 3`` in all ``8`` null cases (4 catalogs x 2 atoms);
3. ``ln BF(child/root) > 0`` in both injected cases;
4. ``|ln BF - ln BF_SDDR| <= max(0.3, 2 sqrt(sigma^2 + sigma_SDDR^2))`` in
   every null case (MODEL_COMPARISON_MATH.md 9.1(8); ``sigma_SDDR`` is the
   bootstrap standard deviation of the Savage-Dickey estimate).

The expected case counts of items 2 and 3 follow the plan: ``n_catalogs x
len(atoms)`` null cases and ``len(atoms)`` injected ones.

Injection strengths: the conditional profile likelihood of each slope (other
hyperparameters at the truth, the partner intercept profiled) on 48-event v2
catalogs drawn from the child model gave slope widths of about 0.18
(``chi_mu_q_slope``) and 0.04-0.09 (``beta_q_m1_slope``, growing with the
slope). Its approximation of ``ln BF`` was positive in every probed catalog:
0.54-4.97 at ``chi_mu_q_slope = 0.55`` (9 catalogs) and 0.51-9.73 at
``beta_q_m1_slope = 0.25`` and 0.3 (6 and 9 catalogs)
(gwpop-search-data/validation/phase3c_injection_strength_probe/). The marginal
evidence is lower than this conditional approximation, so the injected cases
are a weak check of power, not of calibration.
"""

from __future__ import annotations

from dataclasses import dataclass, field, fields as dataclass_fields, replace
import json
import math
from pathlib import Path
from typing import ClassVar, Mapping, Sequence

import numpy as np

from .campaign import _derived_seed, recovery_seed_pairs
from .dynesty_backend import (
    DynestyConfig,
    DynestyResult,
    _json_sha256,
    prior_transform_for,
    run_dynesty_population,
)
from .phase3_ns import (
    DEFAULT_IMPORTANCE_DRAWS,
    DEFAULT_RHAT_DRAWS_PER_RUN,
    DEFAULT_SIGMA_NS_KAPPA_HAT,
    NSRecoveryAcceptanceCriteria,
    PHASE3_ROOT_SEED,
    _atomic_write_json,
    _common_names,
    _finite_or_none,
    _generate_catalog,
    _hbi_config_payload,
    assess_ns_fit,
    default_phase3_dynesty_config,
    default_phase3_survey_config,
    ns_evidence_sigma,
    phase3_hbi_config,
    plan_dynesty_config,
    slices_for_ndim,
    summarize_ns_fit,
    write_or_verify_plan,
)
from .priors import PriorSpec, serialize_prior_map

EVIDENCE_CHECK_FORMAT_VERSION = "gwpop-search-phase3-evidence-check-1.0"
EVIDENCE_CHECK_PLAN_FORMAT_VERSION = "gwpop-search-phase3-evidence-check-plan-1.0"
NS_FIT_SUMMARY_FORMAT_VERSION = "gwpop-search-ns-fit-summary-1.0"

EVIDENCE_CHECK_ATOMS = ("chieff.mean.linear_q", "pairing.beta.linear_m1")
ATOM_SLOPE_PARAMETERS = {
    "chieff.mean.linear_q": "chi_mu_q_slope",
    "pairing.beta.linear_m1": "beta_q_m1_slope",
}
INJECTION_FRACTION_OF_UPPER_BOUND = 0.9
ROOT_LABEL = "root"

SLICES_RULE_PER_MODEL = "2*(3+ndim)"
SLICES_RULE_FIXED = "fixed"

ROOT_EQUIVALENCE_ATOL = 1e-10
ROOT_EQUIVALENCE_PRIOR_DRAWS = 16
DEFAULT_SDDR_BOOTSTRAP = 200

EVIDENCE_CHECK_PLAN_NAME = "evidence_check_plan.json"
EVIDENCE_CHECK_SUMMARY_NAME = "evidence_check_summary.json"
FIT_SUMMARY_NAME = "fit_summary.json"


def _mutations_by_id():
    from gwpop_search.grammar import DEFAULT_MUTATIONS

    return {mutation.mutation_id: mutation for mutation in DEFAULT_MUTATIONS}


def _validated_atoms(atoms: Sequence[str]) -> tuple[str, ...]:
    atoms = tuple(str(atom) for atom in atoms)
    if not atoms:
        raise ValueError("at least one atom is required")
    if len(set(atoms)) != len(atoms):
        raise ValueError(f"atoms must be unique; got {atoms}")
    unknown = sorted(set(atoms) - set(ATOM_SLOPE_PARAMETERS))
    if unknown:
        raise ValueError(
            f"unsupported atom(s) {unknown}; the evidence check covers {EVIDENCE_CHECK_ATOMS}"
        )
    return atoms


def atom_slope_prior(atom: str) -> PriorSpec:
    """The registered child prior of ``atom``'s slope (a ``PriorSpec``)."""
    mutation = _mutations_by_id()[atom]
    prior = mutation.prior_updates[ATOM_SLOPE_PARAMETERS[atom]]
    return PriorSpec(prior.family, **dict(prior.parameters))


def default_injection_strengths(atoms: Sequence[str] = EVIDENCE_CHECK_ATOMS) -> dict[str, float]:
    """``0.9 x`` the upper bound of each atom's registered slope prior (0.54, 0.27)."""
    out = {}
    for atom in _validated_atoms(atoms):
        prior = atom_slope_prior(atom)
        out[atom] = round(INJECTION_FRACTION_OF_UPPER_BOUND * float(prior.high), 12)
    return out


def evidence_check_model_specs(atoms: Sequence[str] = EVIDENCE_CHECK_ATOMS):
    """``{"root": baseline_model_spec(), atom: registered mutation applied to the root}``."""
    from gwpop_search.grammar import apply_mutation, baseline_model_spec

    atoms = _validated_atoms(atoms)
    root = baseline_model_spec()
    mutations = _mutations_by_id()
    specs = {ROOT_LABEL: root}
    for atom in atoms:
        child = apply_mutation(root, mutations[atom])
        added = sorted(set(child.priors) - set(root.priors))
        if added != [ATOM_SLOPE_PARAMETERS[atom]] or set(root.priors) - set(child.priors):
            raise RuntimeError(f"{atom} is not the nested one-slope extension of the root")
        specs[atom] = child
    return specs


# ---------------------------------------------------------------------------
# Pass rule
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class EvidenceCheckPassRule:
    """Pre-declared engineering pass rule of the Phase-3c evidence check."""

    FORMAT_VERSION: ClassVar[str] = "gwpop-search-phase3-evidence-check-rule-1.0"

    max_null_ln_bf: float = 3.0
    min_injected_ln_bf: float = 0.0
    sddr_tolerance_floor: float = 0.3
    sddr_tolerance_sigmas: float = 2.0
    expected_null_cases: int = 8
    expected_injected_cases: int = 2
    sigma_ns_kappa_hat: float = DEFAULT_SIGMA_NS_KAPPA_HAT
    fit_criteria: NSRecoveryAcceptanceCriteria = field(
        default_factory=NSRecoveryAcceptanceCriteria.f3_level
    )

    def __post_init__(self) -> None:
        for name in ("max_null_ln_bf", "min_injected_ln_bf"):
            if not math.isfinite(float(getattr(self, name))):
                raise ValueError(f"{name} must be finite")
        if not float(self.sddr_tolerance_floor) > 0.0:
            raise ValueError("sddr_tolerance_floor must be positive")
        if not float(self.sddr_tolerance_sigmas) > 0.0:
            raise ValueError("sddr_tolerance_sigmas must be positive")
        if not float(self.sigma_ns_kappa_hat) > 0.0:
            raise ValueError("sigma_ns_kappa_hat must be positive")
        for name in ("expected_null_cases", "expected_injected_cases"):
            if int(getattr(self, name)) < 0:
                raise ValueError(f"{name} cannot be negative")
        if not isinstance(self.fit_criteria, NSRecoveryAcceptanceCriteria):
            raise TypeError("fit_criteria must be NSRecoveryAcceptanceCriteria")

    @classmethod
    def for_plan(cls, *, n_catalogs: int, n_atoms: int, **overrides) -> "EvidenceCheckPassRule":
        """The rule of a check with ``n_catalogs`` catalogs and ``n_atoms`` atoms.

        The case counts are a property of the plan, not a constant: a check run
        with fewer catalogs must not fail on the count alone.
        """
        payload = {
            "expected_null_cases": int(n_catalogs) * int(n_atoms),
            "expected_injected_cases": int(n_atoms),
        }
        payload.update(overrides)
        return cls(**payload)

    def to_dict(self) -> dict[str, object]:
        payload: dict[str, object] = {"format_version": self.FORMAT_VERSION}
        for item in dataclass_fields(self):
            value = getattr(self, item.name)
            payload[item.name] = (
                value.to_dict() if isinstance(value, NSRecoveryAcceptanceCriteria) else value
            )
        return payload

    @classmethod
    def from_dict(cls, payload: Mapping[str, object]) -> "EvidenceCheckPassRule":
        values = dict(payload)
        version = values.pop("format_version", None)
        if version != cls.FORMAT_VERSION:
            raise ValueError(f"unsupported evidence-check rule format {version!r}")
        known = {item.name for item in dataclass_fields(cls)}
        unknown = sorted(set(values) - known)
        if unknown:
            raise ValueError(f"unknown evidence-check rule field(s) {unknown}")
        if "fit_criteria" in values:
            values["fit_criteria"] = NSRecoveryAcceptanceCriteria.from_dict(values["fit_criteria"])
        return cls(**values)


def _rule_check(name: str, value, limit, comparison: str, **extra) -> dict[str, object]:
    ok = value is not None and not isinstance(value, bool) and math.isfinite(float(value))
    if ok:
        value = float(value)
        passed = {
            "lt": value < float(limit),
            "gt": value > float(limit),
            "le": value <= float(limit),
            "ge": value >= float(limit),
            "eq": value == float(limit),
        }[comparison]
    else:
        passed = False
    record = {
        "name": name,
        "value": value if ok else None,
        "comparison": comparison,
        "limit": float(limit),
        "passed": bool(passed),
    }
    record.update(extra)
    return record


def evaluate_evidence_check_rule(
    null_cases: Sequence[Mapping[str, object]],
    injected_cases: Sequence[Mapping[str, object]],
    fit_assessments: Sequence[Mapping[str, object]],
    rule: EvidenceCheckPassRule | None = None,
) -> dict[str, object]:
    """Apply the pre-declared pass rule.

    ``null_cases``/``injected_cases`` need ``catalog``, ``atom``, ``ln_bf`` and
    ``ln_bf_sigma``; null cases also ``sddr["ln_bf"]`` and, for the full
    tolerance of MODEL_COMPARISON_MATH.md 9.1(8), ``sddr["bootstrap_std"]``.
    ``fit_assessments`` are :func:`assess_ns_fit` results (with a ``passed``
    flag) of every fit.

    The SDDR tolerance is ``max(floor, sigmas * sqrt(sigma^2 +
    sigma_SDDR^2))``. A missing ``sigma`` fails the check (the tolerance is
    then undefined); a missing ``sigma_SDDR`` only drops that term, which makes
    the tolerance tighter, and is recorded in a note.
    """
    rule = EvidenceCheckPassRule() if rule is None else rule
    null_cases = [dict(case) for case in null_cases]
    injected_cases = [dict(case) for case in injected_cases]
    n_fits = len(fit_assessments)
    n_valid = sum(bool(item["passed"]) for item in fit_assessments)
    checks = [
        {
            "name": "all_fits_numerically_valid",
            "value": f"{n_valid}/{n_fits}",
            "comparison": "all",
            "limit": "F3-level gates",
            "passed": bool(n_fits > 0 and n_valid == n_fits),
        },
        _rule_check("n_null_cases", len(null_cases), rule.expected_null_cases, "eq"),
        _rule_check("n_injected_cases", len(injected_cases), rule.expected_injected_cases, "eq"),
    ]
    for case in null_cases:
        label = f"null.{case['catalog']}.{case['atom']}"
        checks.append(_rule_check(f"{label}.ln_bf", case.get("ln_bf"), rule.max_null_ln_bf, "lt"))
    for case in injected_cases:
        label = f"injected.{case['atom']}"
        checks.append(
            _rule_check(f"{label}.ln_bf", case.get("ln_bf"), rule.min_injected_ln_bf, "gt")
        )
    for case in null_cases:
        label = f"null.{case['catalog']}.{case['atom']}"
        sigma = _finite_or_none(case.get("ln_bf_sigma"))
        sddr = dict(case.get("sddr") or {})
        sigma_sddr = _finite_or_none(sddr.get("bootstrap_std"))
        difference = None
        if case.get("ln_bf") is not None and sddr.get("ln_bf") is not None:
            difference = abs(float(case["ln_bf"]) - float(sddr["ln_bf"]))
        floor = float(rule.sddr_tolerance_floor)
        # MODEL_COMPARISON_MATH.md 9.1(8):
        # |ln BF_NS - ln BF_SDDR| <= 2 sqrt(sigma_NS,a^2/R_a + sigma_NS,b^2/R_b + sigma_SDDR^2).
        combined = (
            None
            if sigma is None
            else math.sqrt(sigma**2 + (0.0 if sigma_sddr is None else sigma_sddr**2))
        )
        tolerance = (
            floor
            if combined is None
            else max(floor, float(rule.sddr_tolerance_sigmas) * combined)
        )
        record = _rule_check(
            f"{label}.sddr_agreement",
            difference,
            tolerance,
            "le",
            ln_bf_sigma=sigma,
            sddr_bootstrap_std=sigma_sddr,
            combined_sigma=combined,
        )
        if sigma is None:
            record["passed"] = False
            record["note"] = "ln BF sigma unavailable"
        elif sigma_sddr is None:
            record["note"] = "SDDR bootstrap std unavailable; tolerance omits sigma_SDDR"
        checks.append(record)
    return {
        "rule": rule.to_dict(),
        "passed": bool(all(item["passed"] for item in checks)),
        "checks": checks,
    }


# ---------------------------------------------------------------------------
# Root equivalence and Savage-Dickey
# ---------------------------------------------------------------------------


def root_equivalence_check(
    posterior,
    selection,
    *,
    seed: int,
    truth: Mapping[str, float] | None = None,
    n_prior_draws: int = ROOT_EQUIVALENCE_PRIOR_DRAWS,
    atol: float = ROOT_EQUIVALENCE_ATOL,
) -> dict[str, object]:
    """Compare ``compile_model_spec(baseline_model_spec())`` with ``GwcatChiEffBBHModel``.

    Both densities are evaluated on every PE and selection sample at the
    truth (default: the Phase-3 truth) and at ``n_prior_draws`` seeded draws
    of the root hyperprior. Passes iff the priors are identical, the support
    (finite vs ``-inf``) agrees everywhere, no value is NaN/+inf and every
    finite difference is at most ``atol``.
    """
    from gwpop_search.grammar import baseline_model_spec
    from gwpop_search.models import (
        DEFAULT_BASELINE_HYPERPARAMETERS,
        GwcatChiEffBBHModel,
        compile_model_spec,
    )

    from .model_spec import prior_specs_from_model_spec
    from .priors import BASELINE_SYNTHETIC_PRIORS

    spec = baseline_model_spec()
    declarative = compile_model_spec(spec)
    reference = GwcatChiEffBBHModel()
    priors = prior_specs_from_model_spec(spec)
    priors_equal = priors == dict(BASELINE_SYNTHETIC_PRIORS)
    context_equal = all(
        declarative.to_config()[key] == reference.to_config()[key]
        for key in ("cosmology", "zmax", "q_floor", "redshift_quadrature_order")
    )
    names, transform = prior_transform_for(priors)
    rng = np.random.default_rng(int(seed))
    truth = dict(DEFAULT_BASELINE_HYPERPARAMETERS if truth is None else truth)
    points = [{name: float(truth[name]) for name in names}]
    for _ in range(int(n_prior_draws)):
        values = transform(rng.random(len(names)))
        points.append({name: float(values[k]) for k, name in enumerate(names)})
    blocks = {"pe": posterior.samples, "selection": selection.samples}
    max_abs = 0.0
    n_values = 0
    n_finite = 0
    support_mismatches = 0
    invalid_values = 0
    for hp in points:
        for samples in blocks.values():
            a = np.asarray(declarative(samples, hp), dtype=np.float64)
            b = np.asarray(reference(samples, hp), dtype=np.float64)
            if a.shape != b.shape:
                raise RuntimeError(f"density shapes differ: {a.shape} vs {b.shape}")
            invalid_values += int(np.count_nonzero(np.isnan(a) | np.isposinf(a)))
            invalid_values += int(np.count_nonzero(np.isnan(b) | np.isposinf(b)))
            finite_a = np.isfinite(a)
            finite_b = np.isfinite(b)
            support_mismatches += int(np.count_nonzero(finite_a != finite_b))
            both = finite_a & finite_b
            n_values += int(a.size)
            n_finite += int(np.count_nonzero(both))
            if both.any():
                max_abs = max(max_abs, float(np.max(np.abs(a[both] - b[both]))))
    passed = bool(
        priors_equal
        and context_equal
        and support_mismatches == 0
        and invalid_values == 0
        and max_abs <= float(atol)
    )
    return {
        "declarative_model_hash": spec.model_hash,
        "n_points": len(points),
        "n_values": n_values,
        "n_finite": n_finite,
        "priors_equal": bool(priors_equal),
        "context_equal": bool(context_equal),
        "support_mismatches": support_mismatches,
        "nan_or_posinf_values": invalid_values,
        "max_abs_difference": max_abs,
        "atol": float(atol),
        "passed": passed,
    }


def _pooled_weighted_parameter(results: Sequence[DynestyResult], index: int):
    """Dead + final live points of every run, each run's weights normalized to 1/R."""
    values, weights = [], []
    for result in results:
        w = np.asarray(result.weights, dtype=float)
        values.append(np.asarray(result.samples, dtype=float)[:, index])
        weights.append(w / (np.sum(w) * len(results)))
    return np.concatenate(values), np.concatenate(weights)


def _kde_log_density(values, weights, at: float):
    from scipy.stats import gaussian_kde

    keep = weights > 0.0
    kde = gaussian_kde(values[keep], weights=weights[keep])
    density = float(kde(np.asarray([float(at)]))[0])
    bandwidth = float(np.sqrt(kde.covariance[0, 0]))
    return (math.log(density) if density > 0.0 else float("-inf")), bandwidth, float(kde.neff)


def savage_dickey_ln_bf(
    results: Sequence[DynestyResult],
    parameter: str,
    prior: PriorSpec,
    *,
    null_value: float = 0.0,
    n_bootstrap: int = DEFAULT_SDDR_BOOTSTRAP,
    seed: int,
) -> dict[str, object]:
    """Savage-Dickey ``ln BF(child/root) = ln pi(null) - ln p(null | D)``.

    ``p(null | D)`` is a Gaussian KDE (``scipy.stats.gaussian_kde``, Scott's
    rule with the Kish size) of the child's marginal posterior of
    ``parameter``, built from the weighted dead and final live points of all
    runs, each run normalized to weight ``1/R`` (the equal-weight mixture of
    the runs). No boundary correction is applied: ``null`` must lie strictly
    inside a uniform prior. ``bootstrap_std`` is the standard deviation of the
    estimate over ``n_bootstrap`` resamplings (with replacement, within each
    run) of the weighted points.
    """
    results = list(results)
    names = _common_names(results)
    if parameter not in names:
        raise ValueError(f"{parameter!r} is not a parameter of the runs {names}")
    if prior.family != "uniform":
        raise ValueError("the Savage-Dickey check is implemented for uniform slope priors")
    if not float(prior.low) < float(null_value) < float(prior.high):
        raise ValueError("the null value must lie strictly inside the prior (no reflection)")
    index = names.index(parameter)
    ln_prior = -math.log(float(prior.high) - float(prior.low))
    values, weights = _pooled_weighted_parameter(results, index)
    ln_density, bandwidth, neff = _kde_log_density(values, weights, null_value)
    mean = float(np.sum(weights * values))
    std = float(np.sqrt(np.sum(weights * (values - mean) ** 2)))
    rng = np.random.default_rng(int(seed))
    boot = []
    for _ in range(int(n_bootstrap)):
        v_b, w_b = [], []
        for result in results:
            samples = np.asarray(result.samples, dtype=float)[:, index]
            w = np.asarray(result.weights, dtype=float)
            pick = rng.integers(0, samples.size, samples.size)
            total = float(np.sum(w[pick]))
            if total <= 0.0:
                continue
            v_b.append(samples[pick])
            w_b.append(w[pick] / (total * len(results)))
        if len(v_b) != len(results):
            continue
        ln_b, _, _ = _kde_log_density(np.concatenate(v_b), np.concatenate(w_b), null_value)
        if math.isfinite(ln_b):
            boot.append(ln_prior - ln_b)
    ln_bf = ln_prior - ln_density if math.isfinite(ln_density) else None
    return {
        "parameter": parameter,
        "null_value": float(null_value),
        "prior": prior.to_dict(),
        "ln_prior_density": ln_prior,
        "ln_posterior_density": _finite_or_none(ln_density),
        "ln_bf": _finite_or_none(ln_bf),
        "bootstrap_std": float(np.std(boot, ddof=1)) if len(boot) > 1 else None,
        "n_bootstrap": len(boot),
        "kde": "scipy.stats.gaussian_kde (Scott's rule, NS weights, runs pooled with equal weight)",
        "bandwidth": bandwidth,
        "n_effective": neff,
        "posterior_mean": mean,
        "posterior_std": std,
        "posterior_mass_above_null": float(np.sum(weights[values > float(null_value)])),
    }


# ---------------------------------------------------------------------------
# Running the check
# ---------------------------------------------------------------------------


def generate_injected_catalog(*, atom: str, strength: float, data_seed: int, survey_config):
    """A catalog drawn from ``atom``'s child model (slope ``strength``, root truth otherwise).

    Uses the grammar-matched structured generator
    :func:`gwpop_search.scouts.synthetic.generate_structured_scout_dataset`,
    which draws the events from the child population and then applies the
    survey's own observation model through the Phase-3 synthetic machinery
    (``noisy_observation``: one noise realisation per event and injection,
    detection on the observed data, PE drawn given the observation; the
    selection injections are the survey's baseline-proxy draws). The
    structured draw density equals the compiled child density
    (``tests/test_phase3_evidence_check.py``).
    """
    from gwpop_search.scouts.synthetic import (
        StructuredScoutInjection,
        generate_structured_scout_dataset,
    )

    from .synthetic import OBSERVATION_MODEL_NOISY

    atom = _validated_atoms([atom])[0]
    dataset = generate_structured_scout_dataset(
        seed=int(data_seed),
        injection=StructuredScoutInjection(atom, float(strength)),
        survey_config=survey_config,
    )
    noisy = survey_config.observation_model == OBSERVATION_MODEL_NOISY
    if noisy and dataset.event_observations is None:  # pragma: no cover - generator contract
        raise RuntimeError("structured generator ignored observation_model='noisy_observation'")
    parameter = ATOM_SLOPE_PARAMETERS[atom]
    if float(dataset.truth_hyperparameters[parameter]) != float(strength):
        raise RuntimeError(f"injected catalog does not record {parameter}={strength}")
    return dataset


def _model_dynesty_config(base: DynestyConfig, ndim: int, slices_rule: str) -> DynestyConfig:
    if slices_rule == SLICES_RULE_PER_MODEL:
        if base.sample not in ("slice", "rslice"):
            raise ValueError("the per-model slices rule needs sample='slice' or 'rslice'")
        return replace(base, slices=slices_for_ndim(ndim))
    if slices_rule == SLICES_RULE_FIXED:
        return base
    raise ValueError(f"unknown slices rule {slices_rule!r}")


def _fit_seed(sampler_seed: int, model_hash: str, repeat: int) -> int:
    return _derived_seed(int(sampler_seed), f"evidence-check:{model_hash}", int(repeat))


def build_evidence_check_plan(
    *,
    n_catalogs: int,
    root_seed: int,
    repeats: int,
    survey_config,
    dynesty_config: DynestyConfig,
    slices_rule: str,
    hbi_config,
    atoms: Sequence[str],
    injection_strengths: Mapping[str, float],
    rule: EvidenceCheckPassRule,
    importance_draws: int = DEFAULT_IMPORTANCE_DRAWS,
    rhat_draws_per_run: int = DEFAULT_RHAT_DRAWS_PER_RUN,
    sddr_bootstrap: int = DEFAULT_SDDR_BOOTSTRAP,
) -> dict[str, object]:
    """The ``gwpop-search-phase3-evidence-check-plan-1.0`` payload (JSON-normalized)."""
    from gwpop_search.models import DEFAULT_BASELINE_HYPERPARAMETERS

    from .model_spec import prior_specs_from_model_spec

    atoms = _validated_atoms(atoms)
    n_catalogs = int(n_catalogs)
    if n_catalogs < 1:
        raise ValueError("n_catalogs must be positive")
    repeats = int(repeats)
    if repeats < 2:
        raise ValueError("repeats must be >= 2")
    if set(injection_strengths) != set(atoms):
        raise ValueError("injection_strengths must give exactly one strength per atom")
    specs = evidence_check_model_specs(atoms)
    models = {}
    for label, spec in specs.items():
        priors = prior_specs_from_model_spec(spec)
        models[label] = {
            "model_hash": spec.model_hash,
            "mutation_id": None if label == ROOT_LABEL else label,
            "ndim": len(priors),
            "priors": serialize_prior_map(priors),
            "dynesty_config": plan_dynesty_config(
                _model_dynesty_config(dynesty_config, len(priors), slices_rule)
            ),
        }
    injected = []
    for atom in atoms:
        strength = float(injection_strengths[atom])
        prior = atom_slope_prior(atom)
        if not float(prior.low) <= strength <= float(prior.high):
            raise ValueError(f"injection strength {strength} of {atom} lies outside its prior")
        injected.append(
            {
                "atom": atom,
                "parameter": ATOM_SLOPE_PARAMETERS[atom],
                "strength": strength,
                "data_seed": _derived_seed(
                    int(root_seed), f"evidence-check-injection-data:{atom}", 0
                ),
                "sampler_seed": _derived_seed(
                    int(root_seed), f"evidence-check-injection-sampler:{atom}", 0
                ),
            }
        )
    plan = {
        "format_version": EVIDENCE_CHECK_PLAN_FORMAT_VERSION,
        "root_seed": int(root_seed),
        "n_catalogs": n_catalogs,
        "repeats": repeats,
        "atoms": list(atoms),
        "catalogs": [
            {"label": f"catalog_{i:03d}", "data_seed": int(data), "sampler_seed": int(sampler)}
            for i, (data, sampler) in enumerate(
                recovery_seed_pairs(n_catalogs, root_seed=int(root_seed))
            )
        ],
        "injected": injected,
        "injection_rule": f"slope = {INJECTION_FRACTION_OF_UPPER_BOUND} x upper prior bound "
        "unless overridden; other hyperparameters at the root truth",
        "survey_config": survey_config.to_dict(),
        "hbi_config": _hbi_config_payload(hbi_config),
        "dynesty_config_base": plan_dynesty_config(dynesty_config),
        "slices_rule": slices_rule,
        "models": models,
        "truth_hyperparameters": {
            name: float(value) for name, value in DEFAULT_BASELINE_HYPERPARAMETERS.items()
        },
        "diagnostics": {
            "importance_draws": int(importance_draws),
            "rhat_draws_per_run": int(rhat_draws_per_run),
            "sddr_bootstrap": int(sddr_bootstrap),
            "root_equivalence": {
                "atol": ROOT_EQUIVALENCE_ATOL,
                "n_prior_draws": ROOT_EQUIVALENCE_PRIOR_DRAWS,
            },
        },
        "rule": rule.to_dict(),
    }
    return json.loads(json.dumps(plan, sort_keys=True))


def _run_fit(
    fit_dir: Path,
    dataset,
    spec,
    *,
    label: str,
    sampler_seed: int,
    repeats: int,
    config: DynestyConfig,
    hbi_config,
    importance_draws: int,
    rhat_draws_per_run: int,
):
    from gwpop_search.models import compile_model_spec

    from .model_spec import prior_specs_from_model_spec
    from .synthetic import require_population_proxy_coverage

    model = compile_model_spec(spec)
    priors = prior_specs_from_model_spec(spec)
    require_population_proxy_coverage(
        dataset.selection, priors=priors, context=f"Phase-3c evidence check, {label}"
    )
    seeds = [_fit_seed(sampler_seed, spec.model_hash, r) for r in range(int(repeats))]
    results = []
    run_dirs = []
    for r, seed in enumerate(seeds):
        relative = f"repeat_{r:03d}"
        results.append(
            run_dynesty_population(
                dataset.posterior,
                dataset.selection,
                model,
                priors,
                seed=int(seed),
                config=config,
                hbi_config=hbi_config,
                run_dir=fit_dir / relative,
            )
        )
        run_dirs.append(relative)
    fit = summarize_ns_fit(
        results,
        dataset.posterior,
        dataset.selection,
        model,
        hbi_config=hbi_config,
        importance_draws=importance_draws,
        importance_seed=_derived_seed(
            int(sampler_seed), f"evidence-check-importance:{spec.model_hash}", 0
        ),
        rhat_draws_per_run=rhat_draws_per_run,
        run_dirs=run_dirs,
    )
    payload = {
        "format_version": NS_FIT_SUMMARY_FORMAT_VERSION,
        "label": label,
        "model_hash": spec.model_hash,
        "repeat_seeds": seeds,
        "dynesty_config": plan_dynesty_config(config),
        "fit": fit,
    }
    _atomic_write_json(fit_dir / FIT_SUMMARY_NAME, payload)
    return results, payload


def ln_bf_sigma_ns(
    child_evidence: Mapping[str, object],
    root_evidence: Mapping[str, object],
    *,
    kappa_hat: float = DEFAULT_SIGMA_NS_KAPPA_HAT,
) -> dict[str, object]:
    """``sigma(ln BF)`` from nested sampling, MODEL_COMPARISON_MATH.md 9.1(6).

    ``sigma^2 = sigma_NS,child^2 / R_child + sigma_NS,root^2 / R_root``. The
    Monte-Carlo-likelihood term ``sigma_MC,ab^2`` of 9.1(6) is not computed by
    this module (it needs the posterior-averaged normalized weights of both
    models) and is not included; the result is therefore a nested-sampling-only
    error. It is the right quantity for the SDDR cross-check (9.1(8)), whose
    two routes share the same Monte-Carlo likelihood (design Sec. 4.4).
    """
    child = ns_evidence_sigma(child_evidence, kappa_hat=kappa_hat)
    root = ns_evidence_sigma(root_evidence, kappa_hat=kappa_hat)
    means = (child["sigma_of_mean"], root["sigma_of_mean"])
    sigma = None if any(value is None for value in means) else float(math.hypot(*means))
    return {
        "formula": "MODEL_COMPARISON_MATH.md 9.1(6), sigma_MC term not included",
        "sigma": sigma,
        "child": child,
        "root": root,
        "includes_sigma_mc": False,
    }


def _bayes_factor_case(
    *,
    kind: str,
    catalog: str,
    atom: str,
    root_fit: Mapping[str, object],
    child_fit: Mapping[str, object],
    child_results: Sequence[DynestyResult],
    sddr_seed: int,
    sddr_bootstrap: int,
    kappa_hat: float = DEFAULT_SIGMA_NS_KAPPA_HAT,
    truth_slope: float | None = None,
) -> dict[str, object]:
    root_evidence = dict(dict(root_fit["fit"])["evidence"])
    child_evidence = dict(dict(child_fit["fit"])["evidence"])
    ln_bf = float(child_evidence["mean"]) - float(root_evidence["mean"])
    budget = ln_bf_sigma_ns(child_evidence, root_evidence, kappa_hat=kappa_hat)
    sigma = budget["sigma"]
    errors = (child_evidence.get("conservative_error"), root_evidence.get("conservative_error"))
    sigma_task_text = None if any(e is None for e in errors) else float(math.hypot(*errors))
    parameter = ATOM_SLOPE_PARAMETERS[atom]
    sddr = savage_dickey_ln_bf(
        child_results,
        parameter,
        atom_slope_prior(atom),
        n_bootstrap=sddr_bootstrap,
        seed=sddr_seed,
    )
    case = {
        "kind": kind,
        "catalog": catalog,
        "atom": atom,
        "parameter": parameter,
        "root_model_hash": root_fit["model_hash"],
        "child_model_hash": child_fit["model_hash"],
        "data_identity": dict(root_fit["fit"])["data_identity"],
        "root_log_evidence": float(root_evidence["mean"]),
        "root_conservative_error": errors[1],
        "child_log_evidence": float(child_evidence["mean"]),
        "child_conservative_error": errors[0],
        "ln_bf": ln_bf,
        "ln_bf_sigma": sigma,
        "ln_bf_sigma_budget": budget,
        # The literal formula of the original task text: the single-run error,
        # not the error of the mean of R runs. Recorded for traceability; no
        # check uses it.
        "ln_bf_sigma_task_text": sigma_task_text,
        "sddr": sddr,
        "ln_bf_minus_sddr": None if sddr["ln_bf"] is None else ln_bf - float(sddr["ln_bf"]),
    }
    if truth_slope is not None:
        names = _common_names(child_results)
        draws = np.concatenate([np.asarray(r.posterior_samples, float) for r in child_results])
        values = draws[:, names.index(parameter)]
        q05, q50, q95 = np.quantile(values, [0.05, 0.5, 0.95])
        case["injected_slope"] = float(truth_slope)
        case["slope_posterior"] = {
            "q05": float(q05),
            "median": float(q50),
            "q95": float(q95),
            "truth_in_90pct_interval": bool(q05 <= truth_slope <= q95),
        }
    return case


def run_evidence_check(
    root: str | Path,
    *,
    n_catalogs: int = 4,
    root_seed: int = PHASE3_ROOT_SEED,
    repeats: int = 2,
    survey_config=None,
    dynesty_config: DynestyConfig | None = None,
    slices_rule: str = SLICES_RULE_PER_MODEL,
    hbi_config=None,
    atoms: Sequence[str] = EVIDENCE_CHECK_ATOMS,
    injection_strengths: Mapping[str, float] | None = None,
    rule: EvidenceCheckPassRule | None = None,
    importance_draws: int = DEFAULT_IMPORTANCE_DRAWS,
    rhat_draws_per_run: int = DEFAULT_RHAT_DRAWS_PER_RUN,
    sddr_bootstrap: int = DEFAULT_SDDR_BOOTSTRAP,
) -> dict[str, object]:
    """Run/resume the Phase-3c evidence check and write ``evidence_check_summary.json``.

    Layout: ``null/catalog_XXX/<label>/repeat_YYY`` and
    ``injected/<atom>/<label>/repeat_YYY`` (``<label>`` is ``root`` or the
    atom's mutation id), each fit with a ``fit_summary.json``. The plan
    (``evidence_check_plan.json``) is written or verified before any
    computation; completed runs are reused untouched and interrupted runs
    resume from their dynesty checkpoint.
    """
    root = Path(root)
    atoms = _validated_atoms(atoms)
    survey_config = default_phase3_survey_config() if survey_config is None else survey_config
    dynesty_config = default_phase3_dynesty_config() if dynesty_config is None else dynesty_config
    hbi_config = phase3_hbi_config() if hbi_config is None else hbi_config
    strengths = (
        default_injection_strengths(atoms)
        if injection_strengths is None
        else {str(k): float(v) for k, v in injection_strengths.items()}
    )
    # The expected case counts follow the plan, so a check with fewer catalogs
    # is not failed on the count alone. An explicit rule is honoured but must
    # agree with the plan.
    expected = (int(n_catalogs) * len(atoms), len(atoms))
    if rule is None:
        rule = EvidenceCheckPassRule.for_plan(n_catalogs=int(n_catalogs), n_atoms=len(atoms))
    elif (rule.expected_null_cases, rule.expected_injected_cases) != expected:
        raise ValueError(
            f"the pass rule expects {rule.expected_null_cases} null and "
            f"{rule.expected_injected_cases} injected cases, but this plan produces "
            f"{expected[0]} and {expected[1]}"
        )
    plan = build_evidence_check_plan(
        n_catalogs=n_catalogs,
        root_seed=root_seed,
        repeats=repeats,
        survey_config=survey_config,
        dynesty_config=dynesty_config,
        slices_rule=slices_rule,
        hbi_config=hbi_config,
        atoms=atoms,
        injection_strengths=strengths,
        rule=rule,
        importance_draws=importance_draws,
        rhat_draws_per_run=rhat_draws_per_run,
        sddr_bootstrap=sddr_bootstrap,
    )
    write_or_verify_plan(root / EVIDENCE_CHECK_PLAN_NAME, plan)
    specs = evidence_check_model_specs(atoms)
    configs = {
        label: _model_dynesty_config(
            dynesty_config, int(plan["models"][label]["ndim"]), slices_rule
        )
        for label in specs
    }

    def fit(fit_dir, dataset, label, sampler_seed):
        return _run_fit(
            fit_dir,
            dataset,
            specs[label],
            label=label,
            sampler_seed=sampler_seed,
            repeats=repeats,
            config=configs[label],
            hbi_config=hbi_config,
            importance_draws=importance_draws,
            rhat_draws_per_run=rhat_draws_per_run,
        )

    equivalence = []
    fits = []
    null_cases = []
    injected_cases = []

    for catalog in plan["catalogs"]:
        label = catalog["label"]
        sampler_seed = int(catalog["sampler_seed"])
        dataset, _ = _generate_catalog(int(catalog["data_seed"]), survey_config)
        check = root_equivalence_check(
            dataset.posterior,
            dataset.selection,
            seed=_derived_seed(sampler_seed, "root-equivalence", 0),
        )
        equivalence.append({"catalog": label, **check})
        if not check["passed"]:
            raise RuntimeError(
                f"declarative root and GwcatChiEffBBHModel differ on {label}: {check}"
            )
        base = root / "null" / label
        root_results, root_fit = fit(base / ROOT_LABEL, dataset, ROOT_LABEL, sampler_seed)
        fits.append({"kind": "null", "catalog": label, "label": ROOT_LABEL, "summary": root_fit})
        for atom in atoms:
            child_results, child_fit = fit(base / atom, dataset, atom, sampler_seed)
            fits.append({"kind": "null", "catalog": label, "label": atom, "summary": child_fit})
            null_cases.append(
                _bayes_factor_case(
                    kind="null",
                    catalog=label,
                    atom=atom,
                    root_fit=root_fit,
                    child_fit=child_fit,
                    child_results=child_results,
                    sddr_seed=_derived_seed(sampler_seed, f"evidence-check-sddr:{atom}", 0),
                    sddr_bootstrap=sddr_bootstrap,
                    kappa_hat=rule.sigma_ns_kappa_hat,
                )
            )

    for item in plan["injected"]:
        atom = item["atom"]
        sampler_seed = int(item["sampler_seed"])
        dataset = generate_injected_catalog(
            atom=atom,
            strength=float(item["strength"]),
            data_seed=int(item["data_seed"]),
            survey_config=survey_config,
        )
        check = root_equivalence_check(
            dataset.posterior,
            dataset.selection,
            seed=_derived_seed(sampler_seed, "root-equivalence", 0),
        )
        equivalence.append({"catalog": f"injected/{atom}", **check})
        if not check["passed"]:
            raise RuntimeError(
                f"declarative root and GwcatChiEffBBHModel differ on injected/{atom}: {check}"
            )
        base = root / "injected" / atom
        root_results, root_fit = fit(base / ROOT_LABEL, dataset, ROOT_LABEL, sampler_seed)
        child_results, child_fit = fit(base / atom, dataset, atom, sampler_seed)
        fits.append({"kind": "injected", "catalog": atom, "label": ROOT_LABEL, "summary": root_fit})
        fits.append({"kind": "injected", "catalog": atom, "label": atom, "summary": child_fit})
        injected_cases.append(
            _bayes_factor_case(
                kind="injected",
                catalog=f"injected/{atom}",
                atom=atom,
                root_fit=root_fit,
                child_fit=child_fit,
                child_results=child_results,
                sddr_seed=_derived_seed(sampler_seed, f"evidence-check-sddr:{atom}", 0),
                sddr_bootstrap=sddr_bootstrap,
                kappa_hat=rule.sigma_ns_kappa_hat,
                truth_slope=float(item["strength"]),
            )
        )

    assessments = []
    for item in fits:
        assessment = assess_ns_fit(dict(item["summary"]["fit"]), rule.fit_criteria)
        assessments.append(
            {
                "kind": item["kind"],
                "catalog": item["catalog"],
                "label": item["label"],
                "model_hash": item["summary"]["model_hash"],
                "passed": assessment["passed"],
                "checks": assessment["checks"],
            }
        )
    verdict = evaluate_evidence_check_rule(null_cases, injected_cases, assessments, rule)
    summary = {
        "format_version": EVIDENCE_CHECK_FORMAT_VERSION,
        "plan_sha256": _json_sha256(plan),
        "rule": rule.to_dict(),
        "root_equivalence": equivalence,
        "null_cases": null_cases,
        "injected_cases": injected_cases,
        "fit_assessments": assessments,
        "pass_rule": verdict,
        "evidence_check_passed": verdict["passed"],
    }
    _atomic_write_json(root / EVIDENCE_CHECK_SUMMARY_NAME, summary)
    return summary
